---
on: [push]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - uses: davidslusser/actions_python_ruff@v1.0.1
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: articulate/actions-markdownlint@v1
